package com.ounis.fo2tweaksrditor;

import com.ounis.utils.FramesUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author AndroidDev
 */
public class MainFrame extends javax.swing.JFrame {

    private DefaultListModel lmSections;
    private String fileName;

    private boolean FileLoadErr = false;
    public boolean isFileLoaded() {
        return !this.FileLoadErr;
    }
    
     class BtnDelSectClick implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (lmSections.getSize() >0)
                lmSections.remove(0);
            else
                JOptionPane.showMessageDialog(null,"Lista sekcji jest pusta!!!");
        }
         
     }
    
     
     private ArrayList<String> loadLines(String aFileName) {
        ArrayList<String> res = new ArrayList<String>();
        try {
            BufferedReader textFile = new BufferedReader(
                          new InputStreamReader(new FileInputStream(aFileName)));
            String line;
            String section = "";
            int linenum = 0;
            while((line = textFile.readLine()) != null) {
                linenum++;
                if (line.startsWith("[")) {
                    section = line;
                }
                else {
                    System.out.printf("%d - %d\n", linenum, line.length());
                    if (line.length() == 0) {
                        res.add(String.format(" ",linenum, line));
                        continue;
                    }
                    if (line.startsWith(CONST.REM_CHAR)) {
                        res.add(line);
                        continue;
                    }
                    String keyval = line;
                    String specLine = String.format(CONST.DEF_SPEC_LINE, linenum,section, keyval);
                    res.add(specLine);
                }
            }
        }
        catch (Exception  e) {
            res.clear();
            this.FileLoadErr = true;
        }
         
         return res;
     }
     
    /**
     * Creates new form MainFrame
     */
    public MainFrame(String aFileName) {
        boolean b = true;
        if (!(aFileName == null))
            this.fileName = aFileName;
        else
            this.fileName = CONST.FILE_FO2TWEAKS;
        
        initComponents();
        FramesUtils.centerWindow(this);
        this.setTitle("Fo2Tweaks");
        JOptionPane.showMessageDialog(null, this.fileName);
        
        ArrayList<String> specLines = loadLines(this.fileName);
        lmSections = new DefaultListModel();
        lmSections.addAll(specLines);
        lstSections.setModel(lmSections);
        
        
        //        btnDelSect.addActionListener(new BtnDelSectClick());

        
        }
        
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSections = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstSections = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblSections.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSections.setText("Sekcje");

        lstSections.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(lstSections);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSections, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblSections)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSections;
    private javax.swing.JList<String> lstSections;
    // End of variables declaration//GEN-END:variables
}
